# Generated by Django 2.2.2 on 2019-06-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='voyes',
            new_name='votes',
        ),
    ]
