# Generated by Django 2.2.2 on 2019-06-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Selected_Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_selected', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=None, to='polls.Question')),
            ],
        ),
    ]
