# Generated by Django 2.2.2 on 2019-06-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_user_selected_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_selected_choice',
            name='user',
            field=models.ForeignKey(default=0, on_delete=None, to='polls.User'),
            preserve_default=False,
        ),
    ]
